# Generated by Django 5.2.7 on 2025-10-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('servicio', models.CharField(choices=[('CONT', 'Contabilidad'), ('CG', 'Control de Gestión'), ('PAY', 'Payroll')], max_length=4)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
