# Generated by Django 5.2.7 on 2025-10-21 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_lead_delete_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('CONT', 'Contabilidad'), ('CG', 'Control de Gestión'), ('PAY', 'Payroll'), ('LEGAL', 'Legal/Laboral'), ('CFO', 'CFO as a Service')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='servicio',
        ),
        migrations.AddField(
            model_name='lead',
            name='servicio_interes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coder.servicio'),
        ),
    ]
